"""
LLM-generated strategy: EMA crossover with RSI filter.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class EMAStrategy(IStrategy):
    """
    EMA 9/21 crossover with RSI filter.
    Enters long when EMA9 crosses above EMA21 and RSI is between 45-75.
    Exits when EMA9 crosses below EMA21.
    """

    INTERFACE_VERSION = 3

    minimal_roi = {
        "0": 0.10,
        "60": 0.05,
        "120": 0.02,
        "240": 0.00
    }

    stoploss = -0.05
    trailing_stop = True
    trailing_stop_positive = 0.02
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True

    timeframe = '5m'
    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    startup_candle_count = 30

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['ema9'] = ta.EMA(dataframe, timeperiod=9)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['ema9'] > dataframe['ema21']) &
                (dataframe['ema9'].shift(1) <= dataframe['ema21'].shift(1)) &
                (dataframe['rsi'] > 45) &
                (dataframe['rsi'] < 75) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['ema9'] < dataframe['ema21']) &
                (dataframe['ema9'].shift(1) >= dataframe['ema21'].shift(1)) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1
        return dataframe
