"""
LLM-generated strategy: RSI + MACD crossover with ATR stop-loss.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class LLMStrategy(IStrategy):
    """
    Simple RSI + MACD crossover strategy with ATR-based stop-loss.
    """

    # Strategy parameters
    rsi_period = 14
    rsi_overbought = 70
    rsi_oversold = 30
    macd_fast = 12
    macd_slow = 26
    macd_signal = 9
    atr_period = 14
    atr_multiplier = 2.0

    # Freqtrade interface
    INTERFACE_VERSION = 3

    # Minimal ROI (disabled — rely on signals)
    minimal_roi = {
        "0": 0.10,
        "30": 0.05,
        "60": 0.02,
        "120": 0.00
    }

    # Stoploss (will be overridden per-trade by custom_stoploss)
    stoploss = -0.10

    # Trailing stop
    trailing_stop = True
    trailing_stop_positive = 0.02
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True

    # Timeframe
    timeframe = '5m'

    # Run "populate_indicators" only for new candle
    process_only_new_candles = True

    # These values can be overridden in config
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count = 30

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Add indicators."""
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=self.rsi_period)

        # MACD
        macd = ta.MACD(dataframe, fastperiod=self.macd_fast,
                       slowperiod=self.macd_slow, signalperiod=self.macd_signal)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        # ATR for custom stop-loss
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=self.atr_period)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Define entry signals."""
        dataframe.loc[
            (
                (dataframe['rsi'] < self.rsi_oversold) &
                (dataframe['macd'] > dataframe['macdsignal']) &
                (dataframe['macd'].shift(1) <= dataframe['macdsignal'].shift(1)) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Define exit signals."""
        dataframe.loc[
            (
                (dataframe['rsi'] > self.rsi_overbought) &
                (dataframe['macd'] < dataframe['macdsignal']) &
                (dataframe['macd'].shift(1) >= dataframe['macdsignal'].shift(1)) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1

        return dataframe

    def custom_stoploss(self, pair: str, trade, current_time, current_rate, current_profit, **kwargs):
        """Dynamic ATR-based stop-loss."""
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        if dataframe is None or dataframe.empty:
            return self.stoploss

        last_candle = dataframe.iloc[-1].squeeze()
        atr = last_candle['atr']
        if pd.isna(atr) or atr == 0:
            return self.stoploss

        # Stop-loss distance as negative percentage from entry
        stop_price = trade.open_rate - (self.atr_multiplier * atr)
        stop_pct = (stop_price / trade.open_rate) - 1
        return stop_pct
