"""
LLM-generated strategy: Bollinger Bands mean reversion with RSI confirmation and ATR stop-loss.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class LLMStrategy(IStrategy):
    """
    Bollinger Bands mean-reversion strategy with RSI confirmation and ATR-based stop-loss.
    Enters long when price touches lower band and RSI is oversold.
    Exits when price touches upper band and RSI is overbought.
    """

    # Strategy parameters
    bb_period = 20
    bb_std = 2.0
    rsi_period = 14
    rsi_overbought = 70
    rsi_oversold = 30
    atr_period = 14
    atr_multiplier = 2.0

    # Freqtrade interface
    INTERFACE_VERSION = 3

    # Minimal ROI (disabled — rely on signals)
    minimal_roi = {
        "0": 0.10,
        "60": 0.05,
        "120": 0.02,
        "240": 0.00
    }

    # Stoploss (will be overridden per-trade by custom_stoploss)
    stoploss = -0.05

    # Trailing stop
    trailing_stop = True
    trailing_stop_positive = 0.02
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True

    # Timeframe
    timeframe = '5m'

    # Run "populate_indicators" only for new candle
    process_only_new_candles = True

    # These values can be overridden in config
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count = 30

    use_custom_stoploss = True

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Add indicators."""
        # Bollinger Bands
        bollinger = ta.BBANDS(dataframe, timeperiod=self.bb_period, nbdevup=self.bb_std, nbdevdn=self.bb_std)
        dataframe['bb_lower'] = bollinger['lowerband']
        dataframe['bb_middle'] = bollinger['middleband']
        dataframe['bb_upper'] = bollinger['upperband']

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=self.rsi_period)

        # ATR for custom stop-loss
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=self.atr_period)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Define entry signals."""
        dataframe.loc[
            (
                (dataframe['close'] <= dataframe['bb_lower']) &
                (dataframe['rsi'] < self.rsi_oversold) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Define exit signals."""
        dataframe.loc[
            (
                (dataframe['close'] >= dataframe['bb_upper']) &
                (dataframe['rsi'] > self.rsi_overbought) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1

        return dataframe

    def custom_stoploss(self, pair: str, trade, current_time, current_rate, current_profit, **kwargs):
        """Dynamic ATR-based stop-loss."""
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        if dataframe is None or dataframe.empty:
            return self.stoploss

        last_candle = dataframe.iloc[-1].squeeze()
        atr = last_candle['atr']
        if pd.isna(atr) or atr == 0:
            return self.stoploss

        # Stop-loss distance as negative percentage from entry
        stop_price = trade.open_rate - (self.atr_multiplier * atr)
        stop_pct = (stop_price / trade.open_rate) - 1
        return stop_pct
