"""
Market regime detection strategy: Bollinger Band squeeze + ADX regime filter.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class RegimeSwitchStrategy(IStrategy):
    """
    Detects market regime and applies appropriate strategy:
    - TREND (ADX > 25): EMA crossover trend-following
    - RANGE (ADX < 20 + BB squeeze): Bollinger Bands mean-reversion
    - Otherwise: no trade
    """

    INTERFACE_VERSION = 3

    minimal_roi = {
        "0": 0.12,
        "120": 0.06,
        "240": 0.03,
        "480": 0.00
    }

    stoploss = -0.06
    trailing_stop = True
    trailing_stop_positive = 0.03
    trailing_stop_positive_offset = 0.05
    trailing_only_offset_is_reached = True

    timeframe = '5m'
    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    startup_candle_count = 30

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # EMAs for trend-following
        dataframe['ema9'] = ta.EMA(dataframe, timeperiod=9)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)

        # ADX for regime detection
        dataframe['adx'] = ta.ADX(dataframe, timeperiod=14)

        # Bollinger Bands for mean-reversion
        bollinger = ta.BBANDS(dataframe, timeperiod=20, nbdevup=2.0, nbdevdn=2.0)
        dataframe['bb_lower'] = bollinger['lowerband']
        dataframe['bb_upper'] = bollinger['upperband']
        dataframe['bb_middle'] = bollinger['middleband']
        dataframe['bb_width'] = (dataframe['bb_upper'] - dataframe['bb_lower']) / dataframe['bb_middle']

        # RSI for both regimes
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        # Regime labels
        dataframe['regime_trend'] = dataframe['adx'] > 25
        dataframe['regime_range'] = (dataframe['adx'] < 20) & (dataframe['bb_width'] < 0.05)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Trend-following entry
        trend_entry = (
            (dataframe['ema9'] > dataframe['ema21']) &
            (dataframe['ema9'].shift(1) <= dataframe['ema21'].shift(1)) &
            (dataframe['regime_trend']) &
            (dataframe['rsi'] > 50) &
            (dataframe['volume'] > 0)
        )

        # Mean-reversion entry
        range_entry = (
            (dataframe['close'] <= dataframe['bb_lower']) &
            (dataframe['regime_range']) &
            (dataframe['rsi'] < 35) &
            (dataframe['volume'] > 0)
        )

        dataframe.loc[trend_entry | range_entry, 'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Trend-following exit
        trend_exit = (
            (dataframe['ema9'] < dataframe['ema21']) &
            (dataframe['ema9'].shift(1) >= dataframe['ema21'].shift(1)) &
            (dataframe['volume'] > 0)
        )

        # Mean-reversion exit
        range_exit = (
            (dataframe['close'] >= dataframe['bb_upper']) &
            (dataframe['rsi'] > 65) &
            (dataframe['volume'] > 0)
        )

        dataframe.loc[trend_exit | range_exit, 'exit_long'] = 1
        return dataframe
