"""
LLM-generated strategy: Simple RSI mean reversion.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class SimpleRSIStrategy(IStrategy):
    """
    Simple RSI mean-reversion strategy.
    Enters long when RSI crosses below 30 (oversold).
    Exits when RSI crosses above 70 (overbought) or after ROI/stoploss.
    """

    INTERFACE_VERSION = 3

    minimal_roi = {
        "0": 0.05,
        "60": 0.02,
        "120": 0.01,
        "240": 0.00
    }

    stoploss = -0.03
    trailing_stop = False

    timeframe = '5m'
    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    startup_candle_count = 30

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 70) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1
        return dataframe
