"""
Trend-following strategy: EMA crossover with ADX trend filter.
Generated by autonomy worker for Freqtrade sandbox bakeoff.
"""

from freqtrade.strategy import IStrategy
import pandas as pd
import numpy as np
from pandas import DataFrame

import talib.abstract as ta


class TrendFollowStrategy(IStrategy):
    """
    EMA 9/21 crossover with ADX trend strength filter.
    Enters long when EMA9 crosses above EMA21 and ADX > 25 (strong trend).
    Exits when EMA9 crosses below EMA21 or trend weakens (ADX < 20).
    """

    INTERFACE_VERSION = 3

    minimal_roi = {
        "0": 0.15,
        "120": 0.08,
        "240": 0.04,
        "480": 0.00
    }

    stoploss = -0.08
    trailing_stop = True
    trailing_stop_positive = 0.04
    trailing_stop_positive_offset = 0.06
    trailing_only_offset_is_reached = True

    timeframe = '5m'
    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    startup_candle_count = 30

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['ema9'] = ta.EMA(dataframe, timeperiod=9)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        dataframe['adx'] = ta.ADX(dataframe, timeperiod=14)
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['ema9'] > dataframe['ema21']) &
                (dataframe['ema9'].shift(1) <= dataframe['ema21'].shift(1)) &
                (dataframe['adx'] > 25) &
                (dataframe['rsi'] > 50) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['ema9'] < dataframe['ema21']) &
                (dataframe['ema9'].shift(1) >= dataframe['ema21'].shift(1)) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1
        return dataframe
